let string = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'
console.log(string.split(','))
console.log(challenge.replace('JavaScript', 'Python'))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt('J'))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
console.log(sentence.indexOf('because'))
console.log(sentence.lastIndexOf('because'))
console.log(sentence.search('because'))
console.log(challenge.split())
console.log(challenge.includes('Script'))
console.log(challenge.substring(3))
console.log(string.substr(0,4))
console.log(challenge.toLowerCase())
console.log(challenge.toUpperCase())
console.log(challenge.length)
console.log(string.repeat(2))
console.log(string.concat('JavaScript'))
console.log(string.match('a'))
console.log(string.endsWith('JavaScript'))
console.log(string.startsWith('30'))
console.log(string)
console.log(string.trim())
console.log(challenge)