const text = 'He earns 5000 euro from salary per month, 10000 euro annual bonus, 15000 euro online courses per month.';
const numbers = text.match(/\d+/g).map(Number);
const totalAnnualIncome = numbers.reduce((total, num) => total + num, 0);
console.log(totalAnnualIncome);
const sentence = 'Love is the best thing in this world. Some found their love and some are still looking for their love.';
const wordToFind = 'love';
const regex = new RegExp('\\b' + wordToFind + '\\b', 'gi'); 
const count = (sentence.match(regex) || []).length;
console.log(count); 
const sentence = 'You cannot end a sentence with because because because is a conjunction';
const wordToFind = 'because';
const regex = new RegExp('\\b' + wordToFind + '\\b', 'gi'); 
const count = (sentence.match(regex) || []).length;
console.log(count); 
